### ISSUE TITLE
support boxen::global::osx_apps in common.yaml

### ISSUE THREAD

**Issue by salimane** [boxen/puppet-brewcask#29]
Currently, I haven't found a way to use homebrew cask from the common.yaml. is it possible to have `boxen::global::osx_apps` a la `boxen::personal::osx_apps`
Thanks

**Comment by blackjid** [comment]
hi! couldn't use `boxen::personal::osx_apps` from `common.yaml`, any idea? thanks!

```yaml
# common.yaml
boxen::personal::osx_apps:
  - google-chrome
  - hipchat
```

```yaml
# config/hiera.yaml
:backends:
  - yaml
:yaml:
  :datadir: "%{::boxen_home}/repo/hiera"
:hierarchy:
  - "users/%{github_login}"
  - common

:merge_behavior: deeper
```

**Comment by salimane** [comment]
@blackjid, I'm guessing you're using the latest version of boxen, puppet-boxen ?

**Comment by blackjid** [comment]
yep, `puppet-boxen -> 3.10.1`  `boxen -> 2.7.0`
