### ISSUE TITLE
Fails silently for installer :manual casks

### ISSUE THREAD

**Issue by danielknell** [boxen/puppet-brewcask#39]
Some casks require a manual action to be run after installing, the output explaining what needs to done is suppressed by boxen meaning these casks "install" but the app is still not available.

an example of such casks in https://github.com/caskroom/homebrew-cask/blob/master/Casks/adobe-creative-cloud.rb

installing manually:

```
$ brew cask install adobe-creative-cloud
==> Downloading https://ccmdls.adobe.com/AdobeProducts/KCCC/1/osx10/CreativeClou
######################################################################## 100.0%
To complete the installation of Cask adobe-creative-cloud, you must also
run the installer at

  '/opt/homebrew-cask/Caskroom/adobe-creative-cloud/latest/Creative Cloud Installer.app'

🍺  adobe-creative-cloud staged at '/opt/homebrew-cask/Caskroom/adobe-creative-cloud/latest' (44 files, 2.9M)
```

**Comment by radeksimko** [comment]
Hmm, good spot.

I would rather see less casks with `:manual` to be honest (i.e. find out how we can automate these), instead of fixing this. :smiley: 

But if you know how to fix it, PRs are welcomed.

**Comment by danielknell** [comment]
I am not sure i understand enough to make the changes but i can try and have a look in the coming week, but piping the stdout from brew to the logs as a notice similar to how the errors are handled would at least mean the messages are visible maybe?

I am agreed on less `:manual` casks  though.

**Comment by radeksimko** [comment]
To be fair I'm not sure that Puppet stdout/stderr should ever be treated as output for the user.
It was IMO designed as log - i.e. machine readable, human readability is a side effect, which is why it will not likely be easy to solve this, but I don't want to discourage you nor treat my opinion as general truth. :wink:

**Comment by danielknell** [comment]
but it is exposed to the user, and in this case something feels better than nothing.
