### ISSUE TITLE
ensure => 'absent' doesn't work

### ISSUE THREAD

**Issue by zhenkyle** [boxen/puppet-brewcask#52]
When I try to uninstall a package with this line in mypersonal.pp (or site.pp):

    package { 'bittorrent': provider=> 'brewcask', ensure => 'absent'}

I got these errors, and uninstall failed:

```
Error: Could not set 'absent' on ensure: wrong number of arguments (4 for 1..2) at 1:/opt/boxen/repo/manifests/zhenkyle.pp
Error: Could not set 'absent' on ensure: wrong number of arguments (4 for 1..2) at 1:/opt/boxen/repo/manifests/zhenkyle.pp
Wrapped exception:
wrong number of arguments (4 for 1..2)
Error: /Stage[main]/Main/Package[bittorrent]/ensure: change from /opt/homebrew-cask/Caskroom/bittorrent/latest to absent failed: Could not set 'absent' on ensure: wrong number of arguments (4 for 1..2) at 1:/opt/boxen/repo/manifests/zhenkyle.pp
```

But when I uninstall with `brew cask` command  by hand, it does work:

    brew cask uninstall bittorrent

---

_Another Note:_

    package { 'bittorrent': provider=> 'brewcask', ensure => 'purged'}

_doesn't work too._

_Happy to log it in over there if you think helpful._

```
Error: Parameter ensure failed on Package[bittorrent]: Provider must have features 'purgeable' to set 'ensure' to 'purged' at /opt/boxen/repo/manifests/zhenkyle.pp:1
Wrapped exception:
Provider must have features 'purgeable' to set 'ensure' to 'purged'
Wrapped exception:
Provider must have features 'purgeable' to set 'ensure' to 'purged'
```

**Comment by jacobbednarz** [comment]
Would you be able to try with the following change?

```diff
diff --git a/lib/puppet/provider/package/brewcask.rb b/lib/puppet/provider/package/brewcask.rb
index 84abd9f..e809bc5 100644
--- a/lib/puppet/provider/package/brewcask.rb
+++ b/lib/puppet/provider/package/brewcask.rb
@@ -53,7 +53,7 @@ Puppet::Type.type(:package).provide :brewcask, :parent => Puppet::Provider::Pack
   end

   def uninstall
-    execute "brew", "uninstall", "--force", resource[:name]
+    execute ["brew", "uninstall", "--force", "Caskroom/cask/#{resource[:name]}"]
   end

   def install_options
```

I made this update to the `install` in #51 however the `uninstall` seemed to work fine without it so I left it.

`purgeable` is expected not to work since there isn't support for it in the provider.

**Comment by zhenkyle** [comment]
Tested with the diff above-mentioned.

Failed with result:

```
Error: Execution of 'brew uninstall --force Caskroom/cask/bittorrent' returned 1: Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Error: /Stage[main]/Main/Package[bittorrent]/ensure: change from /opt/homebrew-cask/Caskroom/bittorrent/0.5.7-1 to absent failed: Execution of 'brew uninstall --force Caskroom/cask/bittorrent' returned 1: Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

Howerver,  the original version of `lib/puppet/provider/package/brewcask.rb` before #51 does work. 

It seems this version of `brewcask.rb` invoked the right `brew cask uninstall <PACKAGE_NAME>` command :satisfied:

**Comment by jacobbednarz** [comment]
The only other thing this could be is the missing `command_opts` at the end however when I was testing this, I never got any through and assumed it was always going to be `nil` for `uninstall`. Can you try this?


```diff
   def uninstall
-    execute "brew", "uninstall", "--force", resource[:name]
+    execute ["brew", "uninstall", "--force", "Caskroom/cask/#{resource[:name]}"], command_opts
   end
```

**Comment by zhenkyle** [comment]
Add missing `command_opts` as above diff works (kind of).

This time I got these errors:
```
Error: Execution of 'brew uninstall --force Caskroom/cask/bittorrent' returned 1: Error: No available formula with the name "caskroom/cask/bittorrent"
Error: /Stage[main]/Main/Package[bittorrent]/ensure: change from /opt/homebrew-cask/Caskroom/bittorrent/latest to absent failed: Execution of 'brew uninstall --force Caskroom/cask/bittorrent' returned 1: Error: No available formula with the name "caskroom/cask/bittorrent"
```

At least , these errors are the same as errors got from run `brew uninstall` command by hand:

```
$ brew uninstall --force Caskroom/cask/bittorrent
Error: No available formula with the name "caskroom/cask/bittorrent"
```

Summing up:

`brew install Caskroom/cask/xxx` works, but `brew uninstall --force Caskroom/cask/xxx` does not. 

And after a little research, I think may be it's not a brew issue.  see caskroom/homebrew-cask#23919 .

**Comment by jacobbednarz** [comment]
The intention I had here was to ensure that it was only adding/removing cask formulae, not just any homebrew formulae. One last try:

```diff
   def uninstall
-    execute "brew", "uninstall", "--force", resource[:name]
+    execute ["brew", "uninstall", "--force", resource[:name], command_opts
   end
```

I'm going to assume it works but just wanna be 100% sure.

**Comment by zhenkyle** [comment]
Tried with:

```diff
   def uninstall
-    execute ["brew", "uninstall", "--force", resource[:name], command_opts
+   execute ["brew", "uninstall", "--force", resource[:name]], command_opts
   end
```

Result: this time no errors happens and ` boxen`  reported with `bittorrent`  package been removed:

```
Notice: /Stage[main]/Main/Package[bittorrent]/ensure: removed
```

But in fact it hasn't been removed, it is still installed. I have confirmed that with `brew cask info bittorrent`.

I'm sorry, but after all these tests( on my box), I still believe that `brew cask uninstall` is the right command instead of `brew uninstall`.

Here's my proof:

```
$ brew uninstall --force bittorrent

$ brew cask info bittorrent
bittorrent: latest
https://www.bittorrent.com/
/usr/local/Caskroom/bittorrent/latest (282 files, 8.7MB)  # <--- proof of present
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/bittorrent.rb
==> Name
BitTorrent
==> Artifacts
```

```
$ brew cask uninstall --force bittorrent
==> Uninstalling Cask bittorrent
==> Running uninstall process for bittorrent; your password may be necessary
==> Removing files:
/Applications/BitTorrent.app

$ brew cask info bittorrent
bittorrent: latest
https://www.bittorrent.com/
Not installed    # <--- proof of absent
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/bittorrent.rb
==> Name
BitTorrent
==> Artifacts
```

And here's `brew` and `brew cask` versions on my box:

```
$ brew --version
Homebrew 1.2.3
Homebrew/homebrew-core (git revision fb65; last commit 2017-06-26)

$ brew cask --version
Homebrew-Cask 1.2.3
caskroom/homebrew-cask (git revision 6696b; last commit 2017-06-26)
```

**Comment by jacobbednarz** [comment]
Addressed in #53 if you'd like to test this one out again. Thanks! ⭐️

**Comment by zhenkyle** [comment]
Hi jacobbednarz, I have viewed #53 and I think it's ok, but I haven't test it out because I don't have Boxen environment now. 

To be honest, I'm using Mike McQuaid's strap.sh now, so sorry. Still I think Boxen is an invaluable configuration management software, and the Boxen community is so lucky to have you. You did a great job,  Brave!

**Comment by jacobbednarz** [comment]
No need to apologise and thanks for the kind words!
